### ISSUE TITLE
環境変数が削除されてしまう

### ISSUE THREAD

**Issue by awayume** [nerrog/Easy-ADBuilder#2]
実行後、一部のシステム環境変数(Path)が全て削除される場合があります。

**Comment by nerrog** [comment]
確認し、問題があれば修正します

**Comment by nerrog** [comment]
この問題をバージョン1.4.0で修正しました
https://github.com/nerrog/Easy-ADBuilder/releases/tag/v1.4.0
https://github.com/nerrog/Easy-ADBuilder/commit/2af8eb026c3d7cbba165862423019d51e6e5c5be
他に問題が無いようでしたら24h後にissuesをクローズさせていただきます

**Comment by awayume** [comment]
ありがとうございました。
